### ISSUE TITLE
Thanks. Error with module...

### ISSUE THREAD

**Issue by Najtram** [goedh452/MMM-Domoticz-ext#1]
Looks really great!

Somehow I don't get it to work. 

`
pi@raspberrypi:~/MagicMirror/config $ pm2 logs mm
[TAILING] Tailing last 15 lines for [mm] process (change the value with --lines option)
/home/pi/.pm2/logs/mm-out.log last 15 lines:
0|mm       | [04.04.2021 18:18.21.887] [LOG]   Loading module helpers ...
0|mm       | [04.04.2021 18:18.21.892] [LOG]   No helper found for module: alert.
0|mm       | [04.04.2021 18:18.22.164] [LOG]   Initializing new module helper ...
0|mm       | [04.04.2021 18:18.22.166] [LOG]   Module helper loaded: updatenotification
0|mm       | [04.04.2021 18:18.22.170] [LOG]   No helper found for module: clock.
0|mm       | [04.04.2021 18:18.22.955] [LOG]   Initializing new module helper ...
0|mm       | [04.04.2021 18:18.22.957] [LOG]   Module helper loaded: calendar
0|mm       | [04.04.2021 18:18.22.966] [LOG]   Loading module helpers ...
0|mm       | [04.04.2021 18:18.22.968] [LOG]   No helper found for module: alert.
0|mm       | [04.04.2021 18:18.22.971] [LOG]   Initializing new module helper ...
0|mm       | [04.04.2021 18:18.22.974] [LOG]   Module helper loaded: updatenotification
0|mm       | [04.04.2021 18:18.22.977] [LOG]   No helper found for module: clock.
0|mm       | [04.04.2021 18:18.22.979] [LOG]   Initializing new module helper ...
0|mm       | [04.04.2021 18:18.22.980] [LOG]   Module helper loaded: calendar
0|mm       | [04.04.2021 18:18.23.449] [LOG]   Launching application.

/home/pi/.pm2/logs/mm-error.log last 15 lines:
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Domoticz-ext/node_helper.js:2:22)
0|mm       |     at Module._compile (internal/modules/cjs/loader.js:968:30)
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10) {
0|mm       |   code: 'MODULE_NOT_FOUND',
0|mm       |   requireStack: [
0|mm       |     '/home/pi/MagicMirror/modules/MMM-Domoticz-ext/node_helper.js',
0|mm       |     '/home/pi/MagicMirror/js/app.js',
0|mm       |     '/home/pi/MagicMirror/js/electron.js',
0|mm       |     '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
0|mm       |     undefined
0|mm       |   ]
0|mm       | }
0|mm       | [04.04.2021 18:18.23.022] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | [04.04.2021 18:18.23.025] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm       | [04.04.2021 18:18.23.499] [WARN]  (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397

`

**Comment by goedh452** [comment]
Could you please post the config for the module? I’ll have a look.

**Comment by Najtram** [comment]
Thanks for replying. Someone is helping me on the MagicMirror forum. Looks like it's the xmlhttprequest. I used the minimal config:
Also see: [Forumpost](https://forum.magicmirror.builders/topic/14616/mmm-domoticz-ext-interact-with-domoticz/6?_=1617568146225)

`
{
  module: "MMM-Domoticz-ext",
  header: "Domoticz",
  position: "bottom_left",
  config: {
    apiBase: "192.168.1.45",
    apiPort: "8080",
    rooms: [
      { idx: "2" }
    ]
  }
},
`

**Comment by goedh452** [comment]
package.json added with dependencies.
