### ISSUE TITLE
Someone posted in MM forum

### ISSUE THREAD

**Issue by Najtram** [goedh452/MMM-Domoticz-ext#2]
Thanks for reacting so fast on my issue. It is solved!

In the meanwhile someone also responded on the MM forum. [See ](https://forum.magicmirror.builders/topic/14616/mmm-domoticz-ext-interact-with-domoticz)

For me this module is a long wish come true! Would it be possible to hide the section titles. (E.g. Utilities). I'd love an option for it. (Especially for the gauge's, because they have own titles).

Thanks again for this awesome plugin.

**Comment by goedh452** [comment]
Check. I'm monitoring the forum.
