### ISSUE TITLE
Log not defined error

### ISSUE THREAD

**Issue by wussuphaters** [goedh452/MMM-Domoticz-ext#3]
Hi. I can't get the module to work, it keeps crashing magicmirror. It seems that it doesn't throw an exception when I put a random port in config.js (module just says Loading... indefinitely), but when I use the right port (e.g. 8080) I get this weird error :

[ERROR] Whoops! There was an uncaught exception...
[ERROR] ReferenceError: Log is not defined
    at exports.XMLHttpRequest.requestData.onreadystatechange (/home/pi/MagicMirror/modules/MMM-Domoticz-ext/node_helper.js:20:15)
    at exports.XMLHttpRequest.dispatchEvent (/home/pi/MagicMirror/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/home/pi/MagicMirror/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Can you help ? thanks

**Comment by goedh452** [comment]
This might be because xmlhttprequest isn’t installed in your system. Can you try running ‘npm install xmlhttprequest’ in the MagicMirror folder and then see if it works?

If this works I will still have to fix the uncaught exception of course.

**Comment by wussuphaters** [comment]
I already installed it. I still ran the install install inside the MM folder, it just updated xmlhttprequest. Launching Magicmirror I get the same error while loading the module.

**Comment by goedh452** [comment]
I fixed the crash of MM. Could you please get the latest code from GitHub? I think the request for data raises an error. The error log should now display the return status of the request. With that it is possible to debug further.

Btw: is Domoticz password protected in your setup? That is nog (yet) supported by the module.

**Comment by wussuphaters** [comment]
Oh that's too bad ! I use password protection to restrict access to some devices (for example devices in bedrooms/personal spaces). Are you planning on adding compatibility in a near future ?

**Comment by goedh452** [comment]
Just to be sure: are you using website protection or Light/Switch Protection? The plugin shouldn't have any problems with Light/Switch Protection, but website protection is not implemented. If you want, I can implement it. That shouldn't be too hard.

**Comment by wussuphaters** [comment]
Yes it would be nice to have website protection compatibility, because your plugin cannot be used by someone who wants to do port forwarding to make his domoticz system accessible from the WAN. One would then just have to create a user specific to the mirror. Am I right or is there something I'm missing ? If not then yes, I would be grateful for you to implement it.

**Comment by goedh452** [comment]
@wussuphaters

I implemented basic authentication for Domoticz. 2 config parameters have been added: apiUser and apiPW for specifying the credentials. It works both for the website protection user as for the users specified in Setup -> More options -> Edit users.

I think best indeed is to create a specifics user for the mirror. Please make sure that this user has access to al the devices the mirror is supposed to display. But entering the credentials for the user of the website protection in the mirror config will also work.

Download the latest code from GitHub, give it a try and let me know if it works.

**Comment by wussuphaters** [comment]
Hi ! Thanks a lot for this implementation ! I tried it but I just cannot get it to work, it says Loading indefinitely and I don't have any error logs in terminal. I am using the 8080 port (default), and the credentials for my mirror user. Do you have any idea where it could be coming from ? Thanks

**Comment by goedh452** [comment]
Could you please post your config for the module? Maybe I can find out what the problem is. 

To be sure: did you assign devices to the mirror user in Domiticz?

**Comment by goedh452** [comment]
No further reaction received.
