### ISSUE TITLE
typos/inconsistencies in help.md

### ISSUE THREAD

**Issue by thatguyinoz** [goedh452/MMM-Domoticz-ext#4]
Hi

thanks for this great MM module.
This issue is mostly to help new users of MagicMirror who may be struggling with config.json issues.
I found a couple of differences between the sample config, documentation and actual code.
the README.md file shows:

**apiIP** but the code needs **apiBase**
**apiPW** but the code needs **apihPW**

The sample configs also reflect this difference.

Thank you for this updated Domoticz module with very nice graphs. :-)

**Comment by goedh452** [comment]
Thanks for the feedback! I changed ApiIP in ApiBase in the readme and apiPW in the code. It was a type in the code itself.
