### ISSUE TITLE
Authentication does not appear to work if Domoticz "website protection" is set to "Login page"

### ISSUE THREAD

**Issue by thatguyinoz** [goedh452/MMM-Domoticz-ext#5]
TCPDump confirms that Authentication is send in base64 form as expected if the config file value apiPW is changed to apihPW however a 401 denied is always returned.
In my initial testing I confirmed that the user was created in the domoticz|setup|more option|setup users and that the user had all devices assigned.
Testing with the Website Protection credentials saved in the settings page still returned a 401 error.

As a workaround i have added the IP address of the MagicMirror to the **Local Networks (no user/password)** exception list on the settings page.

Please let me know if you require further information to resolve this.

**Comment by goedh452** [comment]
@thatguyinoz The base authentication does not work when domoticz protection is set to login page, only with Basic-Auth.

**Comment by thatguyinoz** [comment]
Thanks for explaining that. I'll close this issue.
