### ISSUE TITLE
Action Button

### ISSUE THREAD

**Issue by Fabaude** [goedh452/MMM-Domoticz-ext#6]
Hello goedh452, (I am using Google Translate)
a BIG thank you for this module which works at the top.
I am not an expert in programming but I do it at my own pace ...
I wish I could turn my lights on / off on the Magic Mirror but I can't see my "Actions" devices created with url.
Thank you

**Comment by goedh452** [comment]
I do not use Domoticz anymore so won't be able to maintain this module.
