### ISSUE TITLE
HTTPS not supported?

### ISSUE THREAD

**Issue by Zoonie81** [goedh452/MMM-Domoticz-ext#8]
Hi! I can't seem to establish a connection to Domoticz, the module stays in "loading..". All credentials are OK, and Domo logs say nothing out of the ordinary. My Domoticz server is running HTTPS, is that a problem with this module? I couldn't find any info.

Thanks, Z

**Comment by goedh452** [comment]
The module only supports basic auth. I thinks https will be a problem. I’m no longer using Domoticz so testing for me is not possible anymore.

**Comment by Zoonie81** [comment]
Thanks for the quick reply! Perhaps add this info on the module page for future adventurers?

**Comment by goedh452** [comment]
Good suggestion. I changed the readme.
